name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Project build
      run: mvn --batch-mode --update-snapshots package
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/le-mur:latest
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USERNAME}}/le-mur:latest
